# Generated by Django 6.0.6 on 2026-07-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(
                condition=models.Q(('social_id', ''), _negated=True),
                fields=('social_provider', 'social_id'),
                name='unique_social_provider_identity',
            ),
        ),
    ]
