"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import sys
from datetime import timedelta
from pathlib import Path
from urllib.parse import urlparse
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError

import environ
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False),
    CORS_ALLOW_ALL_ORIGINS=(bool, False),
)
environ.Env.read_env(BASE_DIR / '.env')

RUNNING_TESTS = any(argument in {'test', 'pytest'} for argument in sys.argv)

DEBUG = env.bool('DEBUG', default=False)

SECRET_KEY = env('SECRET_KEY', default='')
if not SECRET_KEY:
    if DEBUG or RUNNING_TESTS:
        SECRET_KEY = 'django-insecure-redeeming-time-test-only-key'
    else:
        raise ImproperlyConfigured('SECRET_KEY must be set when DEBUG=False.')
if not DEBUG and SECRET_KEY.startswith('django-insecure-'):
    raise ImproperlyConfigured('SECRET_KEY must not use a Django development value when DEBUG=False.')

_development_hosts = ['localhost', '127.0.0.1', '[::1]']
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=_development_hosts if DEBUG else [])
render_external_hostname = env('RENDER_EXTERNAL_HOSTNAME', default='')
if render_external_hostname and render_external_hostname not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(render_external_hostname)
if not DEBUG and not RUNNING_TESTS and not ALLOWED_HOSTS:
    raise ImproperlyConfigured('ALLOWED_HOSTS must be set when DEBUG=False.')


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'rest_framework',
    'drf_spectacular',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'accounts',
    'planner',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


DATABASE_URL = env('DATABASE_URL', default='')
if not DATABASE_URL:
    if DEBUG or RUNNING_TESTS:
        DATABASE_URL = f'sqlite:///{BASE_DIR / "db.sqlite3"}'
    else:
        raise ImproperlyConfigured('DATABASE_URL must be set when DEBUG=False.')
if not DEBUG and not RUNNING_TESTS and not DATABASE_URL.startswith(('postgres://', 'postgresql://')):
    raise ImproperlyConfigured('DATABASE_URL must point to PostgreSQL when DEBUG=False.')

DATABASES = {
    'default': env.db_url('DATABASE_URL', default=DATABASE_URL),
}
DATABASES['default']['CONN_MAX_AGE'] = env.int('DB_CONN_MAX_AGE', default=60)
DATABASES['default']['CONN_HEALTH_CHECKS'] = True

CACHE_URL = env('CACHE_URL', default='')
if not CACHE_URL:
    if DEBUG or RUNNING_TESTS:
        CACHE_URL = 'locmemcache://redeeming-time'
    else:
        raise ImproperlyConfigured('CACHE_URL must point to a shared Redis cache when DEBUG=False.')
if not DEBUG and not RUNNING_TESTS and not CACHE_URL.startswith(('redis://', 'rediss://', 'valkey://', 'valkeys://')):
    raise ImproperlyConfigured('CACHE_URL must point to a shared Redis-compatible cache when DEBUG=False.')
CACHES = {
    'default': env.cache_url('CACHE_URL', default=CACHE_URL),
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Password reset emails use Django's built-in SMTP backend in production. Keep
# the feature disabled until a transactional email provider has been configured.
EMAIL_BACKEND = env(
    'EMAIL_BACKEND',
    default='django.core.mail.backends.console.EmailBackend' if DEBUG else 'django.core.mail.backends.smtp.EmailBackend',
)
EMAIL_HOST = env('EMAIL_HOST', default='')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
EMAIL_USE_SSL = env.bool('EMAIL_USE_SSL', default=False)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
EMAIL_TIMEOUT = env.int('EMAIL_TIMEOUT', default=10)
EMAIL_FILE_PATH = env('EMAIL_FILE_PATH', default='/tmp/redeeming-time-emails')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='Redeeming Time <no-reply@redeeming-time.local>')
PASSWORD_RESET_EMAIL_ENABLED = env.bool('PASSWORD_RESET_EMAIL_ENABLED', default=DEBUG)
PASSWORD_RESET_TIMEOUT = env.int('PASSWORD_RESET_TIMEOUT', default=3600)
if PASSWORD_RESET_TIMEOUT <= 0:
    raise ImproperlyConfigured('PASSWORD_RESET_TIMEOUT must be positive.')
EMAIL_VERIFICATION_ENABLED = env.bool('EMAIL_VERIFICATION_ENABLED', default=DEBUG)
EMAIL_VERIFICATION_TIMEOUT = env.int('EMAIL_VERIFICATION_TIMEOUT', default=86_400)
if EMAIL_VERIFICATION_TIMEOUT <= 0:
    raise ImproperlyConfigured('EMAIL_VERIFICATION_TIMEOUT must be positive.')
if EMAIL_TIMEOUT <= 0:
    raise ImproperlyConfigured('EMAIL_TIMEOUT must be positive.')
if EMAIL_USE_TLS and EMAIL_USE_SSL:
    raise ImproperlyConfigured('EMAIL_USE_TLS and EMAIL_USE_SSL cannot both be True.')


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

# Planner dates are currently shared across the product, rather than stored per
# calendar or per user. Keep that operational boundary explicit so rollover and
# daily schedule density use the same day transition as the Korean UI.
PLANNER_TIME_ZONE = env('PLANNER_TIME_ZONE', default='Asia/Seoul')
try:
    ZoneInfo(PLANNER_TIME_ZONE)
except ZoneInfoNotFoundError as exc:
    raise ImproperlyConfigured('PLANNER_TIME_ZONE must be a valid IANA timezone.') from exc

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.User'

CORS_ALLOW_ALL_ORIGINS = env.bool('CORS_ALLOW_ALL_ORIGINS', default=False)
CORS_ALLOWED_ORIGINS = env.list(
    'CORS_ALLOWED_ORIGINS',
    default=(
        [
            'https://redeeming-time.vercel.app',
        ]
        if not DEBUG
        else [
        'http://localhost:5173',
        'http://127.0.0.1:5173',
        'http://localhost:8081',
        'http://127.0.0.1:8081',
        ]
    ),
)
CORS_ALLOW_CREDENTIALS = False
CORS_URLS_REGEX = r'^/api/.*$'

# The OAuth callback always redirects to this fixed, deployment-controlled
# origin. It is deliberately not accepted from a query parameter or state
# value, which prevents callback-code open redirects.
FRONTEND_ORIGIN = env(
    'FRONTEND_ORIGIN',
    default='http://localhost:5173' if DEBUG else 'https://redeeming-time.vercel.app',
).rstrip('/')
_frontend_origin = urlparse(FRONTEND_ORIGIN)
if (
    _frontend_origin.scheme not in {'http', 'https'}
    or not _frontend_origin.netloc
    or _frontend_origin.path not in {'', '/'}
    or _frontend_origin.params
    or _frontend_origin.query
    or _frontend_origin.fragment
):
    raise ImproperlyConfigured('FRONTEND_ORIGIN must be an origin without a path, query, or fragment.')
if not DEBUG and _frontend_origin.scheme != 'https':
    raise ImproperlyConfigured('FRONTEND_ORIGIN must use HTTPS when DEBUG=False.')

SOCIAL_AUTH_GOOGLE_CLIENT_ID = env('SOCIAL_AUTH_GOOGLE_CLIENT_ID', default='')
SOCIAL_AUTH_GOOGLE_CLIENT_SECRET = env('SOCIAL_AUTH_GOOGLE_CLIENT_SECRET', default='')
SOCIAL_AUTH_GOOGLE_REDIRECT_URI = env('SOCIAL_AUTH_GOOGLE_REDIRECT_URI', default='').strip()
SOCIAL_AUTH_KAKAO_CLIENT_ID = env('SOCIAL_AUTH_KAKAO_CLIENT_ID', default='')
SOCIAL_AUTH_KAKAO_CLIENT_SECRET = env('SOCIAL_AUTH_KAKAO_CLIENT_SECRET', default='')
SOCIAL_AUTH_KAKAO_REDIRECT_URI = env('SOCIAL_AUTH_KAKAO_REDIRECT_URI', default='').strip()
SOCIAL_AUTH_STATE_TTL_SECONDS = env.int('SOCIAL_AUTH_STATE_TTL_SECONDS', default=600)
SOCIAL_AUTH_HANDOFF_TTL_SECONDS = env.int('SOCIAL_AUTH_HANDOFF_TTL_SECONDS', default=60)
SOCIAL_AUTH_HTTP_TIMEOUT_SECONDS = env.int('SOCIAL_AUTH_HTTP_TIMEOUT_SECONDS', default=10)

for _redirect_uri_name in ('SOCIAL_AUTH_GOOGLE_REDIRECT_URI', 'SOCIAL_AUTH_KAKAO_REDIRECT_URI'):
    _redirect_uri = globals()[_redirect_uri_name]
    if not _redirect_uri:
        continue
    _parsed_redirect_uri = urlparse(_redirect_uri)
    if _parsed_redirect_uri.scheme not in {'http', 'https'} or not _parsed_redirect_uri.netloc:
        raise ImproperlyConfigured(f'{_redirect_uri_name} must be an absolute HTTP(S) URL.')
    if not DEBUG and _parsed_redirect_uri.scheme != 'https':
        raise ImproperlyConfigured(f'{_redirect_uri_name} must use HTTPS when DEBUG=False.')

if SOCIAL_AUTH_STATE_TTL_SECONDS <= 0:
    raise ImproperlyConfigured('SOCIAL_AUTH_STATE_TTL_SECONDS must be positive.')
if SOCIAL_AUTH_HANDOFF_TTL_SECONDS <= 0:
    raise ImproperlyConfigured('SOCIAL_AUTH_HANDOFF_TTL_SECONDS must be positive.')
if SOCIAL_AUTH_HTTP_TIMEOUT_SECONDS <= 0:
    raise ImproperlyConfigured('SOCIAL_AUTH_HTTP_TIMEOUT_SECONDS must be positive.')

CSRF_TRUSTED_ORIGINS = env.list(
    'CSRF_TRUSTED_ORIGINS',
    default=['https://redeeming-time.vercel.app'] if not DEBUG else [],
)
if not DEBUG and CORS_ALLOW_ALL_ORIGINS:
    raise ImproperlyConfigured('CORS_ALLOW_ALL_ORIGINS must be False when DEBUG=False.')
if not DEBUG and not CORS_ALLOWED_ORIGINS:
    raise ImproperlyConfigured('CORS_ALLOWED_ORIGINS must be set when DEBUG=False.')

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https') if not DEBUG else None
SECURE_SSL_REDIRECT = env.bool('SECURE_SSL_REDIRECT', default=not DEBUG)
SECURE_HSTS_SECONDS = env.int('SECURE_HSTS_SECONDS', default=31_536_000 if not DEBUG else 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=not DEBUG)
SECURE_HSTS_PRELOAD = env.bool('SECURE_HSTS_PRELOAD', default=not DEBUG)
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
X_FRAME_OPTIONS = 'DENY'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'config.pagination.StandardResultsSetPagination',
    'PAGE_SIZE': 100,
    'EXCEPTION_HANDLER': 'config.exceptions.api_exception_handler',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'login': '5/minute',
        'registration': '5/hour',
        'token_refresh': '20/minute',
        'logout': '20/minute',
        'password_change': '5/hour',
        'password_reset_request': '5/hour',
        'password_reset_confirm': '10/hour',
        'email_verification_request': '5/hour',
        'email_verification_confirm': '10/hour',
        'social_auth_start': '10/minute',
        'social_auth_callback': '20/minute',
        'social_auth_exchange': '20/minute',
    },
    'NUM_PROXIES': env.int('NUM_PROXIES', default=1 if not DEBUG else 0),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=14),
    'AUTH_HEADER_TYPES': ('Bearer',),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'CHECK_REVOKE_TOKEN': True,
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Redeeming Time API',
    'DESCRIPTION': 'Django REST Framework API for the Redeeming Time planner.',
    'VERSION': '0.1.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SERVE_PUBLIC': DEBUG,
    'SERVE_PERMISSIONS': ['config.permissions.IsStaffOrDebug'],
    'SERVE_AUTHENTICATION': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
}
