# Generated by Django 6.0.6 on 2026-07-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_alter_task_creator'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(
                condition=models.Q(('is_completed', False)),
                fields=['target_date'],
                name='planner_task_open_due_idx',
            ),
        ),
    ]
